# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    logos_directory: '%kernel.project_dir%/public/uploads/logos'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # para que el metodo "getEntityManager" no sea un metodo undefined
    before_request_listener:
        class: App\EventListener\BeforeRequestListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest
    
    App\Services\ssoService:
        arguments:
            $SSO_URL: '%env(SSO_URL)%'
            $SSO_ENTITY_ID: '%env(SSO_ENTITY_ID)%'
            $SSO_CERT_X509: '%env(SSO_CERT_X509)%'
            $SSO_CERT_PRIVATE_KEY: '%env(SSO_CERT_PRIVATE_KEY)%'

    App\EventListener\UserListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\User'
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\User'

    App\EventListener\ClientListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\Client'
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\Client'

    App\EventListener\ServiceListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\Service'
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\Service'

    App\EventListener\NetworkDeviceListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\NetworkDevice'
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\NetworkDevice'

    App\EventListener\NetworkVirtualSystemListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\NetworkVirtualSystem'
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\NetworkVirtualSystem'

    App\EventListener\NetworkInterfaceListener:
        tags:
        -
            name: 'doctrine.orm.entity_listener'
            event: 'postPersist'
            entity: 'App\Entity\NetworkInterface'
        -
            name: 'doctrine.orm.entity_listener'
            event: 'postUpdate'
            entity: 'App\Entity\NetworkInterface'

    App\EventListener\ActivityTypeListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\ActivityType'
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\ActivityType'

    App\EventListener\EnvironmentListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\Environment'
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\Environment'

    App\EventListener\MaintenanceContractListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\MaintenanceContract'
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\MaintenanceContract'